name: Check examples README manual updates

on:
  pull_request:
    paths:
      - 'examples/README.md'

jobs:
  verification:
    runs-on: ubuntu-latest
    steps:
      - if: contains(github.head_ref, 'automation-examples-readme')
        name: pass
        run: echo "The update is made by the bot, as expected."

      - if: contains(github.head_ref, 'automation-examples-readme') == false
        name: fail
        run: |
          echo "The file examples/README.md should not be manually edited !"
          echo "Please update examples/README_TEMPLATE.md instead"
          exit 1
